my_friend = ['bober', 'zett', 'tross']
print(my_friend)
my_friend.append('nikolai')
print(my_friend)
my_friend.append('koncheniy')
print(my_friend)
my_friend.sort(key=len)
print(my_friend)
my_friend.reverse()
print(my_friend)
my_friend.insert(4, 'piter')
print(my_friend)
print(my_friend.index('piter'))
print(my_friend.index('bober'))
my_friend.append('zett')
print(my_friend.count('zett'))
print(my_friend.count('bober'))
my_friend.copy()
my_friend.clear()
print(my_friend)
my_friend.append('igor')
print(my_friend)
print(len(my_friend))